name: Build Action

on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] # , ubuntu-latest, macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Verify .NET 9
        run: dotnet --version

      - name: Build
        run: dotnet publish -c Release -o ./build --self-contained false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: ./build

      - name: Create ZIP using action-zip
        uses: papeloto/action-zip@v1
        with:
          files: build/*
          dest: ${{ matrix.os }}-${{ github.event.release.tag_name }}.zip

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.os }}-${{ github.event.release.tag_name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
